#!/bin/bash

if [ $# -eq 0 ]; then
  echo "Usage: $0 [start|stop|status]"
  exit 1
fi

if [ "$1" == "start" ]; then
  gunicorn -b localhost:1500 -w 3 -t 122 --log-file=telebot1.log telebot_hook1x:app &
  echo "Gunicorn started."
elif [ "$1" == "stop" ]; then
  # Get the first PID of the Gunicorn process and kill it
  gunicorn_pid=$(ps -e | grep gunicorn | awk 'NR==1 {print $1}')
  if [ -n "$gunicorn_pid" ]; then
    kill "$gunicorn_pid"
    echo "Gunicorn stopped."
  else
    echo "Gunicorn is not running."
  fi
elif [ "$1" == "status" ]; then
  # Show the status of Gunicorn processes
  ps aux | grep gunicorn
else
  echo "Usage: $0 [start|stop|status]"
  exit 1
fi
